# Generated by Django 4.2.5 on 2023-09-30 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="password",
            old_name="body",
            new_name="password",
        ),
    ]
